apiVersion: v2
name: postgresql
description: A Helm chart for deploying Bitnami PostgreSQL
type: application
version: 0.1.0

dependencies:
  - name: postgresql
    version: 12.8.0
    repository: https://charts.bitnami.com/bitnami
