replicaCount: 1

image:
  repository: mrmahy/bots-edi
  tag: latest
  pullPolicy: IfNotPresent

env:
  DB_HOST: postgresql.postgresql.svc.cluster.local
  DB_NAME: botsdb
  DB_USER: bots
  DB_SECRET_NAME: postgresql
  DB_SECRET_KEY: password
