apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bots-edi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mrmahy1980/poc-gitops.git
    targetRevision: HEAD
    path: bots-edi-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: edi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
