replicaCount: 1
image:
  repository: ghcr.io/bots-edi/bots
  tag: 3.2.0
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 8080
  nodePort: 30090
persistence:
  enabled: true
  path: /home/bots/env
  size: 1Gi
