#push_registry: ss151camdmzue2acr.azurecr.io/dflink
push_registry: docker.io/mrmahy1980  # <-- for testing with Docker Hub
images:
  - name: ibm-b2bi/b2bi
    tag: 6.1.2.2
  - name: ibm-b2bi/b2bi-dbsetup
    tag: 6.1.2.2
  - name: ibm-b2bi/b2bi-purge
    tag: 6.1.2.2
  - name: ibm-b2bi/b2bi-ps
    tag: 6.1.2.2
  - name: ibm-b2bi/b2bi-resources
    tag: 6.1.2.2
  - name: opencontent-common-utils
    tag: 1.1.60
