apiVersion: apps/v1
kind: Deployment
metadata:
  name: bots-edi
  labels:
    app: bots-edi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bots-edi
  template:
    metadata:
      labels:
        app: bots-edi
    spec:
      containers:
        - name: bots-edi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9000
