apiVersion: apps/v1
kind: Deployment
metadata:
  name: bots-edi
  labels:
    app: bots-edi
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: bots-edi
  template:
    metadata:
      labels:
        app: bots-edi
    spec:
      containers:
        - name: bots-edi
          image: "{{ .Values.image.repository | default "mrmahy/bots-edi" }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_HOST
              value: {{ .Values.env.DB_HOST | default "postgresql.postgresql.svc.cluster.local" | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.env.DB_NAME | default "botsdb" | quote }}
            - name: DATABASE_USER
              value: {{ .Values.env.DB_USER | default "bots" | quote }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.DB_SECRET_NAME | default "postgresql" | quote }}
                  key: {{ .Values.env.DB_SECRET_KEY | default "password" | quote }}