apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.8.0
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: "auth.database"
          value: "botsdb"
        - name: "auth.username"
          value: "bots"
        - name: "auth.password"
          value: "bots123"
  destination:
    server: https://kubernetes.default.svc
    namespace: bots-edi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
