image:
  repository: mrmahy/bots-edi
  tag: v3
  pullPolicy: Always

env:
  - name: DATABASE_HOST
    value: postgresql.postgresql.svc.cluster.local
  - name: DATABASE_NAME
    value: botsdb
  - name: DATABASE_USER
    value: bots
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgresql
        key: password

service:
  type: ClusterIP
  port: 8080
