name: Download IBM Images

on:
  workflow_dispatch:

jobs:
  download-ibm-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install yq for YAML parsing
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Log in to IBM and Docker Hub
        env:
          ENTITLED_REGISTRY_USER: ${{ secrets.ENTITLED_REGISTRY_USER }}
          ENTITLED_REGISTRY_KEY: ${{ secrets.ENTITLED_REGISTRY_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$ENTITLED_REGISTRY_KEY" | docker login cp.icr.io -u "$ENTITLED_REGISTRY_USER" --password-stdin
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Pull, Tag, and Push IBM Images to Docker Hub
        run: |
          config_file=config/ibm-images-config.yaml
          push_registry=$(yq '.push_registry' "$config_file" | tr -d '"')
          count=$(yq '.images | length' "$config_file")

          for i in $(seq 0 $((count - 1))); do
            name=$(yq ".images[$i].name" "$config_file" | tr -d '"')
            tag=$(yq ".images[$i].tag" "$config_file" | tr -d '"')

            src="cp.icr.io/cp/$name:$tag"
            basename=$(basename "$name")
            dst="$push_registry/$basename:$tag"

            echo "Pulling $src..."
            docker pull $src

            echo "Tagging as $dst..."
            docker tag $src $dst

            echo "Pushing to Docker Hub: $dst"
            docker push $dst
          done
